homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 28.6653
  longitude: -81.4188
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 28
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  customize:
    packages.system: &customize
      package: 'system_Test'

################################################
## group will add a view on the main tab of home assistant
################################################

group:
  default_view:
    name: DEFAULT
    view: yes
    icon: mdi:home
    entities:
      - group.view_test

  View_test:
    name: view test
    entities:
      - sensor.date
      - sensor.time
      - binary_sensor.system_ready
      - sensor.ha_startup_time
      - sensor.ha_version
      - sensor.ha_github_version
      - sensor.ha_pypi_version
      - automation.startup_notification

  view_test:
    view: yes
    name: view_test
    icon: mdi:account-multiple
    entities:
      - group.view_test


################################################
## Automation
################################################

#automation:
#  - alias: startup_notification
#    initial_state: 'on'
#    trigger:
#      - platform: homeassistant
#        event: start
  #  action:
  #    - service: notify.notify
  #      data:
  #        message: "Home Assistant is now up and running."



################################################
## Sensor
################################################

sensor:
  - platform: time_date
    display_options:
      - date
      - time

  - platform: template
    sensors:
      ha_startup_time:
        entity_id: automation.startup_notification
        value_template: >-
          {{ as_timestamp((states.automation.startup_notification.attributes|default).last_triggered|default(None))|timestamp_custom("%b %d %X") or 'unknown' }}

  - platform: rest
    name: ha_github_version
    resource: 'https://api.github.com/repos/home-assistant/home-assistant/releases/latest'
    headers:
      accept: application/vnd.github.v3+json
      content-type: application/json
      user-agent: home-assistant/rest-sensor
    value_template: >-
      {{ value_json.tag_name }}

  - platform: rest
    name: ha_pypi_version
    resource: 'https://pypi.python.org/pypi/homeassistant/json'
    value_template: >-
      {{ value_json.info.version }}






# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
#config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
#updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
#sun:

# Weather Prediction
#sensor:
#  platform: yr

# Text to speech
tts:
  platform: google

#group: !include groups.yaml
