- platform: flux_led
  devices:
    192.168.1.23:
      name: TV Color Lights
    192.168.1.24:
      name: TV Color Lights1
    192.168.1.42:
      name: kitchen cabinet lights
    192.168.1.69:
      name: display light
