#  Monitor internet connection speed.

- platform: template
  sensors:
    a_door_status:
      value_template: '{% if states.binary_sensor.everspring_unknown_type0002_id0002_sensor_15_0 %}
        {% if states.binary_sensor.everspring_unknown_type0002_id0002_sensor_15_0.state == "on" %}
          Open
        {% else %}
          Closed
        {% endif %}
        {% else %}
        n/a
        {% endif %}'
      icon_template: >-
        {%- if states.binary_sensor.everspring_unknown_type0002_id0002_sensor_15_0.state == "on" -%}
          mdi:window-open
        {% else %}
          mdi:logout
        {%- endif -%}
      friendly_name: 'Attic Door Status'
