- platform: template
  name: "Average Temp"
  sensors:
    average_house_temp:
          unit_of_measurement: "°F"
          value_template: >-
            {{ ((float(states.sensor.tv_room_multi_sensor_temperature_32_1.state) + float(states.sensor.kitchen_multi_sensor_temperature_31_1.state) + float(states.sensor.broadlink_torn_temperature.state) + float(states.sensor.game_room_temperature_2.state) + float(states.sensor.monkey_room_temperature.state) + float(states.sensor.hallway_temperature.state) + float(states.sensor.master_bed_temperature.state) + float(states.sensor.nina_room_temperature.state)) / 8) | round(1) }}

- platform: gitter
  api_key: !secret gitter_api
#  room:
