## this is based on a split configuration setup.
## place this code into a seporate yaml file and place it in a folder labled sensor in your root homeassistant location
## add this entry to your configuration file. sensor: !include_dir_merge_list sensors
## alter code below to fit your needs

- platform: template
  sensors:
    garage_door_status:
      value_template: '{% if states.binary_sensor.garage_door_opener_sensor_2_0 %}
        {% if states.binary_sensor.garage_door_opener_sensor_2_0.state == "off" %}
          Closed
        {% else %}
          Open
        {% endif %}
        {% else %}
        n/a
        {% endif %}'
      friendly_name: 'Garage Door Status'
  #    icon_template: '{%- if is_state("sensor.garage_door_status", "open") %}mdi:garage-open{%- elif is_state_attr("sensor.garage_door_status", "battery_status", "Closed")}'


 #icon_template: '{%- if is_state("sensor.battery_ipad", "unknown") %}mdi:battery-unknown{%- elif is_state_attr("device_tracker.ipad", "battery_status", "Charging") %}mdi:battery-charging{%- elif  states.device_tracker.ipad.attributes.battery <= 5 %}mdi:battery-outline{%- elif states.device_tracker.ipad.attributes.battery >= 95 %}mdi:battery{% else %}mdi:battery-{{(states.device_tracker.ipad.attributes.battery|float / 10)|round*10}}{%- endif %}'
