- alias: Pool Door Lights
  trigger:
    - platform: state
      entity_id: binary_sensor.pool_door_sensor_sensor
      to: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.master_bathroom_light, switch.master_bedroom_hallway_light_switch
    - delay:
        minutes: 10
    - service: switch.turn_off
      entity_id: switch.master_bathroom_light, switch.master_bedroom_hallway_light_switch
