- alias: Turn front lights On At Sunset
  hide_entity: false
  trigger:
    platform: sun
    event: sunset
  action:
    service: switch.turn_on
    entity_id: switch.front_lights_switch_28_0, switch.christmas_angel_switch_17_0

- alias: 'front light off'
  trigger:
    platform: sun
    event: sunrise
#    offset: '-07:33:00'
  action:
    service: switch.turn_off
    entity_id: switch.front_lights_switch_28_0, switch.christmas_angel_switch_17_0
