- alias: Turn front lights On At Sunset
  hide_entity: false
  trigger:
    platform: sun
    event: sunset
  action:
    service: homeassistant.turn_on
    entity_id: switch.ge_12722_onoff_relay_switch_switch_28_0

- alias: 'front light off'
  trigger:
    platform: sun
    event: sunrise
#    offset: '-07:33:00'
  action:
    service: homeassistant.turn_off
    entity_id: switch.ge_12722_onoff_relay_switch_switch_28_0
