- alias: Garage Door Reset
  trigger:
    platform: time
    seconds: '/5'
  condition:
    - condition: state
      entity_id: switch.garage_door_opener_switch_2_0
      state: "on"
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.garage_door_opener_switch_2_0
