- alias: Turn on Kitchen light when there is movement
  trigger:
    platform: state
    entity_id: group.kitchen_motion #sensor.tv_room_multi_sensor_burglar_32_10
    state: 'on'
  action:
    service: light.turn_on
    entity_id: group.kitchen_lights
- alias: Turn off Kitchen light when there is no movement
  trigger:
    platform: state
    entity_id: group.kitchen_motion #sensor.kitchen_multi_sensor_burglar_31_10 #sensor.tv_room_multi_sensor_burglar_32_10
    state: 'off'
  action:
    service: light.turn_off
    entity_id: group.kitchen_lights

- alias: Turn on Kitchen light
  trigger:
    platform: state
    entity_id: sensor.fd_motion_status #sensor.tv_room_multi_sensor_burglar_32_10
    state: 'on'
  action:
    service: light.turn_on
    entity_id: group.kitchen_lights
- alias: Turn Kitchen light off
  trigger:
    platform: state
    entity_id: sensor.fd_motion_status #sensor.tv_room_multi_sensor_burglar_32_10
    state: 'off'
  action:
    service: light.turn_off
    entity_id: group.kitchen_lights

- alias: Turn front light on
  trigger:
    platform: state
    entity_id: binary_sensor.front_motion_sensor
    state: 'on'
  action:
    service: light.turn_on
    entity_id: group.kitchen_lights
- alias: Turn front light off
  trigger:
    platform: state
    entity_id: binary_sensor.front_door_sensor_sensor
    state: 'off'
    for:
      minutes: 2
  action:
    service: light.turn_off
    entity_id: group.kitchen_lights

- alias: Turn on master bedroom light when there is movement
  trigger:
    platform: state
    entity_id: sensor.mb_motion_status
    state: 'on'
  condition:
    - condition: template
      value_template: >-
        {%- set hour=(as_timestamp(now())|timestamp_custom("%H"))|int -%}
        {%- if hour >= 10 and hour  <=  22 -%}
          true
        {%- else -%}
          false
        {%- endif %}
  action:
    service: switch.turn_on
    entity_id: switch.master_bedroom_light

- alias: Turn off master bedroom light when there is no movement
  trigger:
    platform: state
    entity_id: sensor.mb_motion_status
    state: 'off'
    for:
      minutes: 2
  condition:
    - condition: template
      value_template: >-
        {%- set hour=(as_timestamp(now())|timestamp_custom("%H"))|int -%}
        {%- if hour >= 10 and hour <= 22 -%}
          true
        {%- else -%}
          false
        {%- endif %}
  action:
    service: switch.turn_off
    entity_id: switch.master_bedroom_light


- alias: Turn on game room light when there is movement
  trigger:
    platform: state
    entity_id: sensor.gr_motion_status
    state: 'on'
  condition:
    - condition: template
      value_template: >-
        {%- set hour=(as_timestamp(now())|timestamp_custom("%H"))|int -%}
        {%- if hour >= 10 and hour  <=  22 -%}
          true
        {%- else -%}
          false
        {%- endif %}
  action:
    service: switch.turn_on
    entity_id: switch.game_room_light

- alias: Turn off game room light when there is no movement
  trigger:
    platform: state
    entity_id: sensor.gr_motion_status
    state: 'off'
    for:
      minutes: 30
  condition:
    - condition: template
      value_template: >-
        {%- set hour=(as_timestamp(now())|timestamp_custom("%H"))|int -%}
        {%- if hour >= 10 and hour  <=  22 -%}
          true
        {%- else -%}
          false
        {%- endif %}
  action:
    service: switch.turn_off
    entity_id: switch.game_room_light

#- alias: 'motion detected'
#  trigger:
#    platform: mqtt
#    topic: 'torn/motion'
#  condition:
#    - condition: state
#      entity_id: device_tracker.torn8o
#      state: 'home'
#  action:
#    service: notify.notify
#    data_template:
#      message: "motion detected: {{ trigger.payload_json['camera'] ~ ' ' ~ trigger.payload_json['time'] ~ ' ' ~ trigger.payload_json['date'] }}"
