 ##############
 #  Presence  #
##############
- alias: Charlie is home
  trigger:
    platform: state
    entity_id: group.charlie
    state: 'home'
  action:
    service: notify.notify
    data:
      message: "Charlie is Home"

- alias: Charlie is away
  trigger:
    platform: state
    entity_id: group.charlie
    state: 'not_home'
  action:
    service: notify.notify
    data:
      message: "charlie is Away"

  ##############
 #  Updates   #
##############
- alias: 'Update Available Notifications'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: persistent_notification.create
    data:
      title: "New Update"
      message: "Update for Home Assistant is available."

  ##############
 #  Network  #
#############
- alias: Z-Wave network is complete
  trigger:
    platform: event
    event_type: zwave.network_ready
  action:
    service: notify.ios_torn8o
    data:
      message: "Z Wave Network is up"
