######################################################################
##  Stuff that needs to happen at 04:30pm.
######################################################################

- alias: 'Timed 4pm'
  trigger:
    - platform: time
      at: '16:00:00'

  action:
    - service: light.turn_on
      entity_id:
        - light.dining_room_level
      #  - light.front_entry_level_6_0
#    - service: switch.turn_on
#      entity_id: switch.kitchen_accents
