homeassistant:
  customize:
    packages.system: &customize
      haaska_hidden: true
      homebridge_hidden: true
      package: 'floorplan'


      name: Demo Floorplan
      image: /local/custom_ui/floorplan/floorplan.svg
      stylesheet: /local/custom_ui/floorplan/floorplan.css

      last_motion_entity: sensor.template_last_motion
      last_motion_class: last-motion

      groups:

        - name: Sensors
          entities:
             - sensor.melbourne_now
          text_template: '${entity.state ? entity.state : "unknown"}'
          class_template: '
            var temp = parseFloat(entity.state.replace("°", ""));
            if (temp < 10)
              return "temp-low";
            else if (temp < 30)
              return "temp-medium";
            else
              return "temp-high";
            '

        - name: Lights
          entities:
             - light.hallway
             - light.living_room
             - light.patio
          states:
            - state: 'on'
              class: 'light-on'
            - state: 'off'
              class: 'light-off'

        - name: Switches
          entities:
             - switch.doorbell
          states:
            - state: 'on'
              class: 'doorbell-on'
            - state: 'off'
              class: 'doorbell-off'

        - name: Alarm Panel
          entities:
             - alarm_control_panel.alarm
          states:
            - state: 'armed_away'
              class: 'alarm-armed'
            - state: 'armed_home'
              class: 'alarm-armed'
            - state: 'disarmed'
              class: 'alarm-disarmed'

        - name: Binary sensors
          entities:
             - binary_sensor.kitchen_multi_sensor_sensor_31_0
             - binary_sensor.front_motion_sensor_42_0
             - binary_sensor.back_motion_sensor_10_0
             - sensor.tv_motion_status
             - sensor.mb_motion_status
             - sensor.mr_motion_status
             - sensor.gr_motion_status
          states:
            - state: 'off'
              class: 'info-light'
            - state: 'on'
              class: 'warning-light'
          state_transitions:
            - name: On to off
              from_state: 'on'
              to_state: 'off'
              duration: 10

        - name: Cameras
          entities:
            - camera.hallway
            - camera.driveway
            - camera.front_door
            - camera.backyard
          states:
            - state: 'idle'
              class: 'camera-idle'
group:
  floorplan:
    entities:
      - sensor.template_last_motion
      - binary_sensor.floorplan

  floorplan_view:
    name: floorplan
    view: yes
    entities:
      - group.floorplan

binary_sensor:
  - platform: mqtt
    state_topic: dummy/floorplan/sensor
    name: Floorplan

sensor:
  - platform: template
    sensors:
      mb_motion_status:
        value_template: '{% if states.sensor.master_bedroom_motion %}
          {% if states.sensor.master_bedroom_motion.state == "motion detected" %}
            on
          {% else %}
            off
          {% endif %}
          {% else %}
          n/a
          {% endif %}'

  - platform: template
    sensors:
      mr_motion_status:
        value_template: '{% if states.sensor.monkey_room_motion %}
          {% if states.sensor.monkey_room_motion.state == "motion detected" %}
            on
          {% else %}
            off
          {% endif %}
          {% else %}
          n/a
          {% endif %}'

  - platform: template
    sensors:
      gr_motion_status:
        value_template: '{% if states.sensor.game_room_motion %}
          {% if states.sensor.game_room_motion.state == "motion detected" %}
            on
          {% else %}
            off
          {% endif %}
          {% else %}
          n/a
          {% endif %}'

  - platform: template
    sensors:
      attic_motion_status:
        value_template: '{% if states.sensor.attic_motion %}
          {% if states.sensor.attic_motion.state == "motion detected" %}
            on
          {% else %}
            off
          {% endif %}
          {% else %}
          n/a
          {% endif %}'

  - platform: template
    sensors:
      kitchen_motion_status:
        value_template: '{% if states.sensor.kitchen_multi_sensor_burglar_31_10 %}
          {% if states.sensor.kitchen_multi_sensor_burglar_31_10.state == "8" %}
            on
          {% else %}
            off
          {% endif %}
          {% else %}
          n/a
          {% endif %}'

  - platform: template
    sensors:
      tv_motion_status:
        value_template: '{% if states.sensor.tv_room_multi_sensor_burglar_32_10 %}
          {% if states.sensor.tv_room_multi_sensor_burglar_32_10.state == "8" %}
            on
          {% else %}
            off
          {% endif %}
          {% else %}
          n/a
          {% endif %}'

  - platform: template
    sensors:
      template_last_motion:
        friendly_name: 'Last Motion'
        value_template: >
          {%- set sensors = [states.sensor.mb_motion_status, states.sensor.tv_motion_status, states.sensor.gr_motion_status, states.sensor.mr_motion_status, states.sensor.kitchen_motion_status, states.binary_sensor.front_motion_sensor_42_0, states.binary_sensor.back_motion_sensor_10_0] %}
          {% for sensor in sensors %}
            {% if as_timestamp(sensor.last_changed) == as_timestamp(sensors | map(attribute='last_changed') | max) %}
              {{ sensor.name }}
            {% endif %}
          {% endfor %}
