############################################################################################
#   @user           :   @torn8o
#   @original Github:   https://github.com/torn8o/Home-AssistantConfig
#   @author         :   torn8o
#   @date           :   04/21/2017
#   @package        :   ios plug and play
#   @description    :   Example to understand Actionable Notifications for IOS.
#                       This is a package file. In order for this to work in your
#                       setup you must have packages set up in your configuration.
#
#                       To set up packages place the following line into the configuration
#                       file under "customize" please view below order.
#
#                       You will then need to make a folder in the ".homeassistant" folder
#                       called packages.
#
#
#   @example        :   homeassistant:
#                         name: your ha name
#                         latitude: !secret home_latitude
#                         longitude: !secret home_longitude
#                         elevation: !secret home_elevation
#                         time_zone: America/Chicago
#                         unit_system: imperial
#                         customize: !include customize.yaml
#                         packages: !include_dir_named packages
############################################################################################


homeassistant:
  customize:
    packages.system: &customize
      haaska_hidden: true
      homebridge_hidden: true
      package: 'ios plug in play'

ios:
  push:
    categories:
      - name: Live
        identifier: 'LIVE_FEED'
        actions:
          - identifier: 'SHOW_FEED'
            title: 'watch live'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'

      - name: Medicine
        identifier: 'TABLET'
        actions:
          - identifier: 'TABLET_TAKEN'
            title: 'Tablet Taken'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'
          - identifier: 'REMIND_LATER'
            title: 'Remind me later'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: no

      - name: Garage
        identifier: 'GARAGE_CLOSE'
        actions:
          - identifier: 'GARAGE_CLOSE'
            title: 'Close Garage'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'
          - identifier: 'REMIND_LATER'
            title: 'Remind me later'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no

      - name: Garage test
        identifier: 'Garage'
        actions:
          - identifier: 'garage'
            title: 'Reminder Garage'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'

      - name: Alarm
        identifier: 'ALARM'
        actions:
          - identifier: 'SOUND_ALARM'
            title: 'Sound Alarm'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'
          - identifier: 'SILENCE_ALARM'
            title: 'Silence Alarm'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes #no
            behavior: 'default' #'textInput'
            textInputButtonTitle: 'Silencio!'
            textInputPlaceholder: 'Placeholder'

group: # will add a view on the main tab of home assistant
  ios_test:
    name: ios_test
    icon: mdi:apple-ios
    view: yes
    entities:
      - automation.Notify_iOS_Actionable_Notifications
      - automation.sound_the_alarm
      - automation.SILENCE_ALARM
      - automation.Notify_camera_Actionable_Notifications
      - automation.notify_door
      - automation.close_garage
      - automation.reset_relays
      - group.zones

automation:
  - alias: Notify iOS Actionable Notifications
    trigger:
      platform: time
      after: '16:00:00'
    action:
      service: notify.ios_torn8o #change to your ios device name or group
      data:
        title: "title area"
        message: "3d press for options"
        data:
          push:
            badge: 0
            sound: US-EN-Morgan-Freeman-Vacate-The-Premises.wav
            category: "ALARM" # Needs to match the top level identifier you used in the ios configuration
          action_data: # Anything passed in action_data will get echoed back to Home Assistant.
            entity_id: camera.cam
            my_custom_data: foo_bar


  - alias: Sound the alarm
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: SOUND_ALARM
    action:
      service: notify.ios_torn8o #change to your ios device name
      data:
        message: "window for sound of alarm"
        data:
          push:
            badge: 0
            sound: US-EN-Daisy-Back-Door-Open.wav

  - alias: silence alarm
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: SILENCE_ALARM
    action:
      service: notify.ios_torn8o #change to your ios device name
      data:
        message: "window for silence alarm"
        data:
          push:
            badge: 0
            sound: US-EN-Alexa-Motion-At-Back-Door.wav
