
light:
  - platform: mqtt_json
    name: "Porch Strip"
    state_topic: "torn/porch"
    command_topic: "torn/porch/set"
    effect: true
    effect_list:
      - bpm
      - candy cane
      - confetti
      - cyclon rainbow
      - dots
      - fire
      - glitter
      - juggle
      - lightning
      - noise
      - police all
      - police one
      - rainbow
      - rainbow with glitter
      - ripple
      - sinelon
      - solid
      - twinkle
    brightness: true
    flash: true
    rgb: true
    optimistic: false
    qos: 0

input_slider:
  porch_animation_speed:
    name: Porch Animation Speed
    initial: 150
    min: 1
    max: 150
    step: 10

automation:
  - alias: "Porch Animation Speed"
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: input_slider.porch_animation_speed
    action:
      - service: mqtt.publish
        data_template:
          topic: "torn/porch/set"
          payload: '{"transition":{{ trigger.to_state.state | int }}}'

group:
  Led_porch:
    view: yes
    name: Led Porch
    entities:
      - input_slider.porch_animation_speed
      - light.porch_strip
