# htis is a package file inorder for this to work in your setup
# you must have packagesset up in your configuration.
#    To set up packages place the following line into the configuation file under
#    customize please view below order. You will then need to make a folder in the .homeassistant folder called poackages.
#
#homeassistant:
#  name: your ha name
#  latitude: !secret home_latitude
#  longitude: !secret home_longitude
#  elevation: !secret home_elevation
#  time_zone: America/Chicago
#  unit_system: imperial
#  customize: !include customize.yaml
#  packages: !include_dir_named packages



homeassistant:
  customize:
    packages.system: &customize
      package: 'package test'


group: # this will add a view on the main tab of home assistant where you will be able to toggle test the aurtomation
  package_test:
    name: package test
    view: yes
    entities:
      - automation.Turn_on_light_when_door_is_opened
      - automation.Turn_off_light_when_door_is_closed


automation:

  - alias: 'Turn on light when door is opened' #this will become the entity name in the states page. ie. automation.Turn_on_light_when_door_is_opened
    trigger:
      platform: state
      entity_id: binary_sensor.door_window_sensor_158d0001549382 # your entity id goes here
      state: 'on'
    condition:
      condition: time
      after: '19:00'
      before: '06:00'
    action:
      service: light.turn_on # the type of service you want to activate
      entity_id: light.gang_lampen # the name of your entity goes here


  - alias: 'Turn off light when door is closed' #this will become the entity name in the states page. ie. automation.Turn_on_light_when_door_is_
    trigger:
      platform: state
      entity_id: binary_sensor.door_window_sensor_158d0001549382 #your entity id goes here
      state: 'off'
    condition:
      condition: time
      after: '19:00'
      before: '06:00'
    action:
      service: light.turn_off # the type of service you want to activate
      entity_id: light.gang_lampen # the name of your entity goes here
