homeassistant:
  customize:
    packages.system: &customize
      haaska_hidden: true
      homebridge_hidden: true
      package: 'room_motion'

group:
  game_room_motion:
    entities:
      - sensor.game_motion
      - sensor.gr_motion_status
      - light.gr_led
      - automation.turn_on_game_room_light_when_there_is_movement
      - automation.turn_off_game_room_light_when_there_is_no_movement

  porch_room_motion:
    entities:
      - sensor.front_p_motion
      - sensor.fd_motion_status
      - automation.binary_turn_on_color_light
      - automation.binary_turn_off_color_lights


  motion:
    name: room motion
    view: yes
    icon: mdi:walk
    entities:
      - group.game_room_motion
      - group.master_room_motion
#      - group.porch_room_motion


sensor:


  - platform: template
    sensors:
      gr_motion_status:
        value_template: '{% if states.sensor.game_motion %}
          {% if states.sensor.game_motion.state == "motion detected" %}
            on
          {% else %}
            off
          {% endif %}
          {% else %}
          n/a
          {% endif %}'

  - platform: template
    sensors:
      attic_motion_status:
        value_template: '{% if states.sensor.attic_motion %}
          {% if states.sensor.attic_motion.state == "motion detected" %}
            on
          {% else %}
            off
          {% endif %}
          {% else %}
          n/a
          {% endif %}'

  - platform: template
    sensors:
      fd_motion_status:
        value_template: '{% if states.sensor.front_p_motion %}
          {% if states.sensor.front_p_motion.state == "motion detected" %}
            on
          {% else %}
            off
          {% endif %}
          {% else %}
          n/a
          {% endif %}'

  - platform: template
    sensors:
      tv_motion_status:
        value_template: '{% if states.sensor.tv_room_multi_sensor_burglar %}
          {% if states.sensor.tv_room_multi_sensor_burglar.state == "8" %}
            on
          {% else %}
            off
          {% endif %}
          {% else %}
          n/a
          {% endif %}'

  - platform: template
    sensors:
      attic_2motion_status:
        value_template: '{% if states.sensor.attic_motion %}
          {% if states.sensor.attic_motion.state == "1" %}
            on
          {% else %}
            off
          {% endif %}
          {% else %}
          n/a
          {% endif %}'

  - platform: template
    sensors:
      dining_motion_status:
        value_template: '{% if states.sensor.dining_motion %}
          {% if states.sensor.dining_motion.state == "1" %}
            on
          {% else %}
            off
          {% endif %}
          {% else %}
          n/a
          {% endif %}'

  - platform: template
    sensors:
      kit_motion_status:
        value_template: '{% if states.sensor.kitchen_multi_sensor_burglar %}
          {% if states.sensor.kitchen_multi_sensor_burglar.state == "8" %}
            on
          {% else %}
            off
          {% endif %}
          {% else %}
          n/a
          {% endif %}'
