homeassistant:
  customize:
    packages.system: &customize
      haaska_hidden: true
      homebridge_hidden: true
      package: 'room_motion'

group:
  game_room_motion:
    entities:
      - sensor.game_motion
      - sensor.gr_motion_status
      - automation.turn_on_game_room_light_when_there_is_movement
      - automation.turn_off_game_room_light_when_there_is_no_movement
  master_room_motion:
    entities:
      - sensor.master_motion
      - sensor.mb_motion_status
      - automation.turn_on_master_bedroom_light_when_there_is_movement
      - automation.turn_off_master_bedroom_light_when_there_is_no_movement
  porch_room_motion:
    entities:
      - sensor.front_p_motion
      - sensor.fd_motion_status
      - automation.binary_turn_on_color_light
      - automation.binary_turn_off_color_lights

  motion:
    name: room motion
    view: yes
    entities:
      - group.game_room_motion
      - group.master_room_motion
      - group.porch_room_motion

sensor:
  - platform: template
    sensors:
      mb_motion_status:
        value_template: '{% if states.sensor.master_motion %}
          {% if states.sensor.master_motion.state == "motion detected" %}
            on
          {% else %}
            off
          {% endif %}
          {% else %}
          n/a
          {% endif %}'

  - platform: template
    sensors:
      gr_motion_status:
        value_template: '{% if states.sensor.game_motion %}
          {% if states.sensor.game_motion.state == "motion detected" %}
            on
          {% else %}
            off
          {% endif %}
          {% else %}
          n/a
          {% endif %}'

  - platform: template
    sensors:
      attic_motion_status:
        value_template: '{% if states.sensor.attic_motion %}
          {% if states.sensor.attic_motion.state == "motion detected" %}
            on
          {% else %}
            off
          {% endif %}
          {% else %}
          n/a
          {% endif %}'

  - platform: template
    sensors:
      fd_motion_status:
        value_template: '{% if states.sensor.front_p_motion %}
          {% if states.sensor.front_p_motion.state == "motion detected" %}
            on
          {% else %}
            off
          {% endif %}
          {% else %}
          n/a
          {% endif %}'

  - platform: template
    sensors:
      tv_motion_status:
        value_template: '{% if states.sensor.tv_room_multi_sensor_burglar_32_10 %}
          {% if states.sensor.tv_room_multi_sensor_burglar_32_10.state == "8" %}
            motion detected
          {% else %}
            standby
          {% endif %}
          {% else %}
          n/a
          {% endif %}'
