

light:
  - platform: mqtt_json
    name: "SN1 LED"
    state_topic: "bruh/sensornode1"
    command_topic: "bruh/sensornode1/set"
    brightness: true
    flash: true
    rgb: true
    optimistic: false
    qos: 0


sensor:

  - platform: mqtt
    state_topic: "torn/wemo_2"
    name: "Master bedroom motion"
    value_template: '{{ value_json.motion }}'

  - platform: mqtt
    state_topic: "torn/wemo_2"
    name: "Master Bedroom Temperature"
    unit_of_measurement: "째F"
    value_template: '{{ value_json.temperature | round(1) }}'

  - platform: mqtt
    state_topic: "torn/wemo_2"
    name: "Master Bedroom Humidity"
    unit_of_measurement: "%"
    value_template: '{{ value_json.humidity | round(1) }}'

  - platform: mqtt
    state_topic: "torn/living_room"
    name: "Living Room motion"
    value_template: '{{ value_json.motion }}'

  - platform: mqtt
    state_topic: "torn/living_room"
    name: "Living Room Temperature"
    unit_of_measurement: "째F"
    value_template: '{{ value_json.temperature | round(1) }}'

  - platform: mqtt
    state_topic: "torn/living_room"
    name: "Living Room Humidity"
    unit_of_measurement: "%"
    value_template: '{{ value_json.humidity | round(1) }}'
  - platform: mqtt
    state_topic: "torn/monkey"
    name: "monkey room motion"
    value_template: '{{ value_json.motion }}'

  - platform: mqtt
    state_topic: "torn/monkey"
    name: "monkey room Temperature"
    unit_of_measurement: "째F"
    value_template: '{{ value_json.temperature | round(1) }}'

  - platform: mqtt
    state_topic: "torn/monkey"
    name: "monkey room Humidity"
    unit_of_measurement: "%"
    value_template: '{{ value_json.humidity | round(1) }}'

  - platform: mqtt
    state_topic: "torn/nina"
    name: "nina room motion"
    value_template: '{{ value_json.motion }}'

  - platform: mqtt
    state_topic: "torn/nina"
    name: "nina room Temperature"
    unit_of_measurement: "째F"
    value_template: '{{ value_json.temperature | round(1) }}'

  - platform: mqtt
    state_topic: "torn/nina"
    name: "nina room Humidity"
    unit_of_measurement: "%"
    value_template: '{{ value_json.humidity | round(1) }}'
group:
  sensor_node_1_card:
    name: Sensor Node 1
    entities:
      - sensor.master_bedroom_motion
      - sensor.Master_bedroom_temperature
      - sensor.master_bedroom_humidity
      - sensor.living_room_motion
      - sensor.living_room_temperature
      - sensor.living_room_humidity
      - sensor.monkey_room_motion
      - sensor.monkey_room_temperature
      - sensor.monkey_room_humidity
      - sensor.nina_room_motion
      - sensor.nina_room_temperature
      - sensor.nina_room_humidity
