## Packages / IFTTT Recipes
homeassistant:

  customize:
    packages.system: &customize
      haaska_hidden: true
      homebridge_hidden: true
      package: 'blue'
# IFTTT Recipes
input_select:
   ifttt_recipes:
     name: IFTTT Recipes
     options:
       - blue
       - green
  #   initial: none
automation:
    - alias: "Flash All House Lights Blue"
      trigger:
        platform: state
        entity_id: input_select.all_blue
        to: "all_blue"
      action:
        service: ifttt.trigger
        data: {"event":"hass_blue_lights"}

    - alias: "Flash Bedroom Lights Blue"
      trigger:
         platform: state
         entity_id: input_select.bedroom_blue
         to: "bedroom_blue"
      action:
         service: ifttt.trigger
         data: {"event":"hass_bedroom_blue"}

group:
    blue_lights:
      control: hidden
      view: yes
 #    icon: mdi:led-on
      name: blue_lights
      entities:
        - group.blue

    blue:
      entities:
        - automation.Flash_All_House_Lights_Blue
        - automation.Flash_Bedroom_Lights_Blue
        - input_select.ifttt_recipes
