homeassistant:
  customize:
    packages.system: &customize
      haaska_hidden: true
      homebridge_hidden: true
      package: 'Test'


group: # will add a view on the main tab of home assistant
  suresh.test:
    name: suresh_test
    view: yes
    entities:
      - input_boolean.tablet_reminder
      - automation.Tablet_Already_taken
      - automation.Remind_Me_Later
      - automation.tablet_reminder
      

input_boolean:
  tablet_reminder:
    name: Tablet Reminder
    initial: on
    icon: mdi:tablet

automation:
  - alias: Tablet Already taken
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: TABLET_TAKEN
    action:
      - service: notify.ios_torn8o
        data:
          message: "Great job!"
      - service: input_boolean.turn_off
        entity_id: input_boolean.tablet_reminder

  - alias: Remind Me Later
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: REMIND_LATER
    action:
      - service: notify.ios_torn8o
        data:
          message: "Will remind you in a few minutes !"

  - alias: tablet reminder
    initial_state: true
    trigger:
      - platform: time
        minutes: '30'
        seconds: '00'
    condition:
      condition: and
      conditions:
      - condition: template
        value_template: '{{ states.input_boolean.tablet_reminder.state == "on" }}'
    action:
      - service: notify.ios_torn8o
        data:
          title: "Tablet Time"
          message: "Please take the tablet!"
          data:
            push:
              category: "TABLET"
            action_data:
              entity_id: foo
              my_custom_data: bar
