###############################################################################
#   @user           :
#   original Github
#   https://github.com/torn8o/Home-AssistantConfig
#   @author         :   torn8o
#   @date           :   06/21/2017
#   @package        :   test
#   @description    :   Example to understand Actionable Notifications for IOS
# htis is a package file inorder for this to work in your setup
# you must have packagesset up in your configuration.
#    To set up packages place the following line into the configuation file under
#    customize please view below order. You will then need to make a folder in the
#    .homeassistant folder called poackages.
#
#homeassistant:
#  name: your ha name
#  latitude: !secret home_latitude
#  longitude: !secret home_longitude
#  elevation: !secret home_elevation
#  time_zone: America/Chicago
#  unit_system: imperial
#  customize: !include customize.yaml
#  packages: !include_dir_named packages
###############################################################################
homeassistant:
  customize:
    packages.system: &customize
      haaska_hidden: true
      homebridge_hidden: true
      package: 'test1'

group: # will add a view on the main tab of home assistant
  test1:
    name: test1
    view: yes
    entities:
      - automation.Test_Notification_Sun_Down

automation:
  - alias: "Test Notification Sun Down"
    initial_state: True
    hide_entity: False
    trigger:
      platform: time
      after: '16:00:00'
    action:
      service: notify.ios_torn8o #notify.html5
      data_template:
          message: "The sun is about down for the night."
